### ISSUE TITLE
SQL Comments in SP's

### ISSUE THREAD

**Issue by rapidvelo** [crimdon/SQLToolkit#26]
Hi there, when executing and updating stored procedures, all the comments are removed.   Is there any support and special character we can add to maintain the comments?

**Comment by crimdon** [comment]
I'm going to rewrite the removal of comments part as its causing issues depending on how people add comments. Will introduce an option not to remove the comments as part of this.

**Comment by crimdon** [comment]
I've added this option with the following caveat:
Comments cannot have the keyword GO in them as this will cause the task to fail when it splits the SQL task into batches

**Comment by rapidvelo** [comment]
Excellent much appreciated.  Thank you!

**Comment by rapidvelo** [comment]
Hi there   We are getting an error when testing, looks like a missing bracket.

2017-06-09T17:00:49.5801023Z ##[error]At E:\agents\agent1\_work\_tasks\RunSqlScripts_a614c885-96bc-42ed-9369-ea36103dd898\2.2.0\RunSqlScripts.ps1:8 char:1
+ {
+ ~
Missing closing '}' in statement block.

At E:\agents\agent1\_work\_tasks\RunSqlScripts_a614c885-96bc-42ed-9369-ea36103dd898\2.2.0\RunSqlScripts.ps1:61 char:2
+ }
+  ~
The Try statement is missing its Catch or Finally block.

**Comment by crimdon** [comment]
Hi there,

Sorry about that. Was just rushing to get finished on Friday afternoon. All fixed and tested now

**Comment by tumm0283** [comment]
Hi Andrew,

We are getting errors executing task RunSQL scripts based on nested comments

example
/*
***********************************************************************************************************************************************************************
Procedure:      SMRGMOImport
Description:
Loading SMF data from OMS systems to Eagle Pace.
used CRD FI SMF as an original template

Parameter:
The parameters are for all of the SMF data elements that are available for the loader
as well as the Error Codes parameter for capturing errors and warnings.

Return Values:
0       -   Successfully completed - Pace expects "0" return value

Debug:
--Insert into ImportExportPace.dbo.tblDebug
--Select 
--VariableName  = '@lsIssuerCd',
--VariableValue = @lsIssuerCd,
--Comments      = 'before Final Issuer Code',
--updateDate    = GETDATE()

Modification History:

Date (mm/dd/yyyy)	Mod By								Reason (ticket, notes, comments)
------------------------------------------------------------------------------------------------------------------------------
11/21/2016         Added mapping  /*116*/ @psResetFrequency
*/

1.	Error : 2017-07-25T20:17:51.4380716Z ##[error]Exception calling "ExecuteNonQuery" with "0" argument(s): "Must declare the scalar variable "@psResetFrequency".
2.	'CREATE/ALTER PROCEDURE' must be the first statement in a query batch."
3.	2017-07-25T20:17:51.4380716Z ##[debug]Processed: ##vso[task.logissue type=error]Exception calling "ExecuteNonQuery" with "0" argument(s): "Must declare the scalar variable "@psResetFrequency".%0D%0A'CREATE/ALTER PROCEDURE' must be the first statement in a query batch."
4.	2017-07-25T20:17:51.4536999Z ##[debug]Processed: ##vso[task.complete result=Failed]


When removed /* */
Added mapping 116 @psResetFrequency  , it worked fine no issues.
I thought the comments issue was fixed with this version 2.5.0, Any advice?

**Comment by crimdon** [comment]
I'll have a look. Was this from the 2.5.3 release from yesterday? Also can you please tell me which task this is from?

**Comment by tumm0283** [comment]
SQL ToolKit version 2.5.0 and Task : Run Sql Scripts
![relno007](https://user-images.githubusercontent.com/29237351/28673892-cb68670c-72b1-11e7-9aed-0ab6863720ac.jpg)
![relno008](https://user-images.githubusercontent.com/29237351/28673893-cb77a5a0-72b1-11e7-9ce6-67a809939a40.jpg)

**Comment by crimdon** [comment]
From your screen shots, it looks like even though the task as updated, the task hasn't. I would try removing that step and re-adding it. It its the latest version, your should also get an option not to remove the comment block.

**Comment by tumm0283** [comment]
got it, that worked.
Thanks again.
