### ISSUE TITLE
"Run SQL Command" doesn't handle a GO at the end of the command

### ISSUE THREAD

**Issue by CodantiM** [crimdon/SQLToolkit#44]
It looks like ~6 months ago someone updated the "Run SQL Command" task to support GO/multiple batches. It just doesn't handle a GO at the end of the script. 

The error is: The error is: 2017-10-23T19:03:42.7334893Z ##[error]Exception calling "ExecuteNonQuery" with "0" argument(s): "Incorrect syntax near 'GO'."

**Comment by crimdon** [comment]
Run SQL Command don't support GO command. The reason for this is the native client in PowerShell doesn't support GO and I had to implement a loop to separate scripts into chucks and process them one at a time. The Invoke-Sqlcmd cmdlet does support GO but had a few bugs around error handling so I stopped using it.

You could save this as a file and use the Run Single SQL Script task.

I didn't add the additional parsing to Run SQL command because I though it would only be used for single line type commands.

**Comment by CodantiM** [comment]
It looks like you updated the Run SQL Command on May 2nd to break it up into chunks to support multiple batches...

The last check-in comment even says: "Fixed issue with EOF and added GO support to RunSqlCommand"

**Comment by crimdon** [comment]
Ah your right! I'd had a quick peek and over looked that. Anyway, after a bit of messing about, I've fixed the issue and it now works when there is a GO command at the end.
