### ISSUE TITLE
"Could not find stored procedure 'Go'." If GO is the last statement in file

### ISSUE THREAD

**Issue by trailmax** [crimdon/SQLToolkit#70]
After a recent update we've started getting this exception:
"Could not find stored procedure 'Go'."

We are running "Run Single SQL Script" of version 2.*. The script is as following:

```Sql
if (select db_id('OB-Config-Testing')) is null
	CREATE DATABASE [OB-Config-Testing]
Go
```

Removing the last GO from the script fixed the issue. 
This seems to be related to this change https://github.com/crimdon/SQLToolkit/commit/385174ccd2a0b86866f3e3acdb66dc8f879566a2

**Comment by jfort62917** [comment]
I don't think the issue is just with a GO at the end of the script.  We are seeing the same issue, starting yesterday, with GO statements in the middle of scripts.  The below script worked prior to yesterday and started having issues.  If we break it up into multiple calls without a GO in it then it works fine.  This was across the board in the extension for SQL command calls and script files that we call.

IF DB_ID('Hangfire') IS NULL
BEGIN
   --Create Hangfire Database
   EXEC('CREATE DATABASE [Hangfire] ON  PRIMARY 
   ( NAME = N''Hangfire'', FILENAME = N''C:\SAN\DATABASE\Database\Hangfire.mdf'' , SIZE = 51200KB , FILEGROWTH = 51200KB )
    LOG ON 
   ( NAME = N''Hangfire_log'', FILENAME = N''C:\SAN\LOGS\Logs\Hangfire_log.ldf'' , SIZE = 165888KB , FILEGROWTH = 10%)')
   
END
ELSE
BEGIN
   print 'Hangfire Database Exists'
END

GO

DECLARE @newDatabase datetime;

SELECT @newDatabase = crdate FROM master.dbo.sysdatabases WHERE name = 'Hangfire'

.......

**Comment by crimdon** [comment]
Sorry guys. I implemented a fix given to me in #69 but didn't have time to test myself. Will back this out today and re-release.

**Comment by avishaiNB** [comment]
Hi,

the remove 

> After a recent update we've started getting this exception:
> "Could not find stored procedure 'Go'."
> 
> We are running "Run Single SQL Script" of version 2.*. The script is as following:
> 
> ```sql
> if (select db_id('OB-Config-Testing')) is null
> 	CREATE DATABASE [OB-Config-Testing]
> Go
> ```
> 
> Removing the last GO from the script fixed the issue.
> This seems to be related to this change [385174c](https://github.com/crimdon/SQLToolkit/commit/385174ccd2a0b86866f3e3acdb66dc8f879566a2)

This does not work with complex script.

**Comment by avishaiNB** [comment]
> Sorry guys. I implemented a fix given to me in #69 but didn't have time to test myself. Will back this out today and re-release.

This caused a major issue, it broke our CD environment .
Please revert or fix as soon as you can.

Regards,
Avishai.

**Comment by romeelian** [comment]
All our deployments were working perfectly on the 29-april. We thought we can re-run our release steps in our acceptance as a preparation for the production next week. What a shock and disappointment. We got failure for all environments, what a shock. Please revert or fix it asap.

**Comment by peterbarendse** [comment]
We have failing release pipelines as well. A quick fix will be highly appreciated.

**Comment by crimdon** [comment]
I've released a new version that reverted the changes yesterday. Sorry for any trouble caused

**Comment by peterbarendse** [comment]
My pipeline is so happy, It works again. Tnx for the quick revert!

**Comment by romeelian** [comment]
YES. thank you for the quick revert. Our release pipeline working like a charm. Everything are green now.

**Comment by avishaiNB** [comment]
Works, 10x!
